--- 
language: python
python: 
- "2.7"
install: pip install -e .
script: python -m gmusicapi.test.integration_test_api
before_install: 
- sudo apt-get update -qq
- sudo apt-get install -qq ubuntu-restricted-extras libav-tools
branches: 
  only: 
  - develop
  - master
env: 
  global: 
  - secure: |-
      L6cpo9OEZpCjeWIyxHLepIIrIcfbHkTWA9FJqp4ajo8m0od02oMWaCTfouiM
      vgfLJdnfFkZH+4J6wQTgjZAfebVJNFReJGiZMTMgUiHFpGQOWxMsMkQdCU9X
      KOaTKLd0+D0kgSjGGj7zqvoAzYwXu3Xi76VpIxcAkluKOUL5IW0=
